spring:
  application.name: sos-id
  datasource:
    url: ${DATABASE_URL:jdbc:h2:mem:sosid;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DATABASE_TO_LOWER=TRUE}
    username: ${DATABASE_USERNAME:sa}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate.ddl-auto: update
    open-in-view: true
    show-sql: true
  data.redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
server:
  error.include-message: never
  forward-headers-strategy: framework


